name: Looty
version: @version@
main: com.derongan.minecraft.looty.Looty
api-version: 1.13

commands:
  looty:
    description: Give a player the specified item
    usage: /looty <item name>
  looties:
    description: List items
    usage: /looties