name: Looty
version: @version@
main: com.derongan.minecraft.looty.Looty
api-version: 1.13

commands:
  relic:
    description: Give a relic
    usage: /relic relic_name
  relics:
    description: List relics
    usage: /relics